name = "Prakitr"
uuid = "1c7989ca-6847-4454-8eb8-073a6c3478e3"
authors = ["pitipatw"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
